[package]
name = "robotica-nodes-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
paho-mqtt = "0.10.0"
tokio = { version = "1.17.0", features = ["full"] }
serde = { version= "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
anyhow = "1.0.56"