[package]
name = "robotica-node-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.16"
paho-mqtt = "0.11.0"
tokio = { version = "1.17.0", features = ["full"] }
serde = { version= "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
anyhow = "1.0.57"
reqwest = "0.11.10"
serde_path_to_error = "0.1.7"
gethostname = "0.2.3"

[workspace]
members = ["brian-node-rust"]